### ISSUE TITLE
 syncGet(key) {     return this.source[key] || null;   }

### ISSUE THREAD

**Issue by x13771944402** [zmkwjx/baikbingo-cache#1]
应该只在key 属性不在source上时返回null,
否则 falsey 的值，都变null了

**Comment by zmkwjx** [comment]
这确实是一个问题，准确的说，当该值为undefined时返回null，否则将导致false或者0或者空字符串时返回为null错误数据，稍晚一些我将对代码进行修改和测试

**Comment by zmkwjx** [comment]
版本1.0.4已解决
