### ISSUE TITLE
parameter setting problem

### ISSUE THREAD

**Issue by hx-yu** [zmkwjx/baikbingo-cache#2]
during initialization, the table name and database name use the same name, which makes the setting of table name invalid

**Comment by hx-yu** [comment]
![image](https://user-images.githubusercontent.com/57945926/171339184-e92639c2-a02a-4caf-b09f-f4d4ff34aeeb.png)

**Comment by zmkwjx** [comment]
感谢您的反馈，稍晚将在下一个版本解决

**Comment by zmkwjx** [comment]
版本1.0.5已解决
